receivers:
  # otlp:
  #   protocols:
  #     grpc:
  #     http:
  fluentforward:
    endpoint: otel-collector:4318
processors:
  batch:
exporters:
  azuremonitor:
    instrumentation_key: INSTRUMENTATION_KYE_PLACEHOLDER
  logging:
    verbosity: detailed

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    # traces:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [azuremonitor, logging]
    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [azuremonitor, logging]
    logs:
      receivers: [fluentforward]
      processors: [batch]
      exporters: [azuremonitor, logging]
